### ISSUE TITLE
Contributing a new Repository

### ISSUE THREAD

**Issue by kclinden** [dev-sec/dev-sec.github.io#46]
Contributing page includes information for contributing to an existing repository, but not for adding a new repository to the project. For example, I have been working on an Inspec Profile for ESXi 6.5. What would be the process for eventually getting this repo added to the dev-sec project?

**Comment by chris-rock** [comment]
@kclinden Thank you for raising this question. Since this happens less frequent, there is no established and documented process yet. I would approach this as follows:

- You make the source available on github?
- The DevSec Maintainers have a look at the repo and thumb up/down the contribution
- The github repo is transferred to DevSec

There are a few additional things to consider:
- We only accept contributions with Apache 2 or MPL 2 license
- We expect contributor to help with maintenance

Does that make any sense?

**Comment by kclinden** [comment]
It does. At what point do you want someone to request the repo be contributed to dev-sec? My ESXi one is still WIP, but at the same time it probably would get done faster due to more contributors with the increased visibility under dev-sec.

**Comment by artem-sidorenko** [comment]
I did a quick look and liked that I saw:-) Very good and mature approaches with solid documentation.

+1 from me

--
Artem Sidorenko

**Comment by chris-rock** [comment]
@kclinden Once the baseline is executable, has some test instructions and its already useful for the community, we can start the process. Ping us once you're ready. 

I also agree with @artem-sidorenko :-)

For naming consistency, we may want to rename the baseline to `esxi-baseline` that covers stig but may include more vmware controls. Other dev-sec baselines have used the same approach. Would that be all right for you @kclinden 

Btw, @kclinden baseline is here https://github.com/kclinden/esxi-65-stig-v1r1

**Comment by chris-rock** [comment]
I see that @aaronlippold snatched the repo away for our friends at Mitre :-) I assume we can close the ticket now. Please reopen if you have any questions.
